### ISSUE TITLE
用户名和密码是什么？

### ISSUE THREAD

**Issue by shuhuan-github** [nodelrd/google-net-browse-helper#1]
![Uploading image.png…]()

**Comment by nodelrd** [comment]
点击取消即可

**Comment by nodelrd** [comment]
如果已经点击了确认，在地址栏输入 chrome://restart 即可恢复使用
此问题来自于分布式服务器 重启 导致

**Comment by nodelrd** [comment]
如果 chrome://restart 不起作用  ，移除扩展 ，重新安装，登陆。目前出现情况极少，持续跟进中

**Comment by shuhuan-github** [comment]
你好，我按照要求重启Chrome、重新安装插件，还是会出现这个东西



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月9日(星期五) 下午4:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [nodelrd/google-net-browse-helper] 用户名和密码是什么？ (#1)






如果铬：//重新启动不起作用,移除扩展,重新安装,登陆.目前出现情况极少,持续跟进中

—
您正在接收此消息，因为您编写了线程。
直接回复此邮件，在GitHub上查看，或取消订阅.

**Comment by nodelrd** [comment]
点击取消

**Comment by nodelrd** [comment]
或者你可以上传完整截图。

**Comment by nodelrd** [comment]
点击取消  是一个必要操作

**Comment by nodelrd** [comment]
在首次出现时点击取消，如果继续出现说明 分布式机器重启导致 
需要重启浏览器，重新安装 插件 然后它可能会继续出现，这个时候就需要 点击取消（相当于首次出现）
这个操作是由于chrome 机制导致的

**Comment by nodelrd** [comment]
点击取消操作，相当于是告诉chrome 我需要将该 操作交给  插件处理

**Comment by nodelrd** [comment]
![image](https://user-images.githubusercontent.com/80455846/115220371-08571800-a13b-11eb-871c-a4801866821e.png)
出现此类框是直接点取消即可
