### ISSUE TITLE
有些时候，发现不能正常连接

### ISSUE THREAD

**Issue by godla** [nodelrd/google-net-browse-helper#2]

**Comment by nodelrd** [comment]
这种情况如果发生在打开chrome的时候
那么这是正常的情况，由于当前版本chrome 启动时，并不会触发扩展授权的机制，导致无法连接，目前反馈给chrome 团队
解决方案是：在地址栏直接打入搜索的内容即可，不要试图输入google.com 或者youtube.com  这类谷歌的网址.一旦您能正常搜索那么后续的操作都会变的正常

**Comment by nodelrd** [comment]
我们将积极的解决这个问题 在未来的版本，以便能获得更好的体验
