### ISSUE TITLE
google scholar 不能够正常登录

### ISSUE THREAD

**Issue by Nicknaam3** [nodelrd/google-net-browse-helper#3]
谷歌搜索是正常的，但是谷歌学术不能登录，请帮忙看一下，谢谢！
![@KLDL6LZSLH IE ~YRM$ %U](https://user-images.githubusercontent.com/83102560/115943628-96d4ec00-a4e3-11eb-8d16-2a51bf191c4d.png)

**Comment by nodelrd** [comment]
Hello ，免费网络，由于使用人数多 ，所以不能正常使用谷歌学术

**Comment by Nicknaam3** [comment]
好的，谢谢

**Comment by Nicknaam3** [comment]
好的，谢谢

**Comment by admin-gh** [comment]
我也遇到了这个问题，请问有解决方案吗
