### ISSUE TITLE
维基百科数学公式不能正常显示

### ISSUE THREAD

**Issue by William-at-github** [nodelrd/google-net-browse-helper#6]
维基百科数学公式不能正常显示

**Comment by nodelrd** [comment]
如果您能提供页面将加速我们修复进度，目前我们在开发mac版本的客户端一遍提供更好的服务

**Comment by William-at-github** [comment]
![优效截图20210717132651](https://user-images.githubusercontent.com/41828839/126026845-e28ba9cd-9318-4c44-8b7f-464c8d8f0e44.png)
![优效截图20210717132708](https://user-images.githubusercontent.com/41828839/126026848-eecde71c-81f9-464c-8d7d-e48b7a03c118.png)
